/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_information_management_system;

import javax.swing.JOptionPane;
import java.sql.SQLException;

public class CourseManagementGUI extends javax.swing.JFrame {

    public CourseManagementGUI() {
        initComponents();
        setSize(790, 542);  
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addCourseButtonActionPerformed = new javax.swing.JButton();
        deleteCourseButtonActionPerformed = new javax.swing.JButton();
        editCourseButtonActionPerformed = new javax.swing.JButton();
        viewCourseButtonActionPerformed = new javax.swing.JButton();
        backButtonActionPerformed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Silom", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Management");

        addCourseButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        addCourseButtonActionPerformed.setText("Add Courses");
        addCourseButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformedActionPerformed(evt);
            }
        });

        deleteCourseButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        deleteCourseButtonActionPerformed.setText("Delete Courses");
        deleteCourseButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseButtonActionPerformedActionPerformed(evt);
            }
        });

        editCourseButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        editCourseButtonActionPerformed.setText("Edit Courses");
        editCourseButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseButtonActionPerformedActionPerformed(evt);
            }
        });

        viewCourseButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        viewCourseButtonActionPerformed.setText("View Courses");
        viewCourseButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCourseButtonActionPerformedActionPerformed(evt);
            }
        });

        backButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        backButtonActionPerformed.setText("Back");
        backButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCourseButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCourseButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCourseButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewCourseButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCourseButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editCourseButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCourseButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteCourseButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformedActionPerformed
        PostLoginMenuGUI postLoginMenu = new PostLoginMenuGUI();
        postLoginMenu.setVisible(true);
        this.dispose(); // Close the StudentManagementGUI
    }//GEN-LAST:event_backButtonActionPerformedActionPerformed

    private void addCourseButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformedActionPerformed
        AddCourseGUI addCourseGUI = new AddCourseGUI();
        addCourseGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addCourseButtonActionPerformedActionPerformed

    private void deleteCourseButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseButtonActionPerformedActionPerformed
        String courseId = JOptionPane.showInputDialog(this, "Enter Course ID to delete:", "Delete Course", JOptionPane.WARNING_MESSAGE);

        if (courseId != null && !courseId.trim().isEmpty()) {
            // Confirm deletion
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the course with ID " + courseId + "?", "Confirm Deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    // Use CourseDataManager to delete the course by ID
                    CourseDataManager courseManager = new CourseDataManager();
                    courseManager.deleteCourse(courseId);

                    JOptionPane.showMessageDialog(this, "Course with ID " + courseId + " deleted successfully.", "Delete Successful", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error deleting course: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Deletion cancelled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid Course ID.", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteCourseButtonActionPerformedActionPerformed

    private void editCourseButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseButtonActionPerformedActionPerformed
        String courseId = JOptionPane.showInputDialog(this, "Enter Course ID to edit:", "Edit Course", JOptionPane.PLAIN_MESSAGE);

        if (courseId != null && !courseId.trim().isEmpty()) {
            try {
                CourseDataManager courseManager = new CourseDataManager();
                Course course = courseManager.getCourseById(courseId); // Method to retrieve a course by ID (implement if not done)

                if (course != null) {
                    // Prompt for new course details
                    String newCourseName = JOptionPane.showInputDialog(this, "Enter new course name:", course.getCourseName());
                    String newTeacherName = JOptionPane.showInputDialog(this, "Enter new teacher name:", course.getTeacherName());

                    // Spinner or input for credits
                    String creditsText = JOptionPane.showInputDialog(this, "Enter new credits:", course.getCredits());

                    try {
                        int newCredits = Integer.parseInt(creditsText);

                        // Update course details
                        course.setCourseName(newCourseName);
                        course.setTeacherName(newTeacherName);
                        course.setCredits(newCredits);

                        courseManager.updateCourse(course); // Method to update course details in database
                        JOptionPane.showMessageDialog(this, "Course updated successfully.", "Edit Successful", JOptionPane.INFORMATION_MESSAGE);
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Credits must be a valid number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Course not found.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error retrieving course: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid Course ID.", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_editCourseButtonActionPerformedActionPerformed

    private void viewCourseButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCourseButtonActionPerformedActionPerformed
        String courseId = JOptionPane.showInputDialog(this, "Enter Course ID to view:", "View Course", JOptionPane.PLAIN_MESSAGE);

        if (courseId != null && !courseId.trim().isEmpty()) {
            try {
                CourseDataManager courseManager = new CourseDataManager();
                Course course = courseManager.getCourseById(courseId); // Retrieve course by ID

                if (course != null) {
                    // Display course details
                    String courseDetails = "Course ID: " + course.getCourseId() + "\n" +
                                           "Course Name: " + course.getCourseName() + "\n" +
                                           "Credits: " + course.getCredits() + "\n" +
                                           "Teacher Name: " + course.getTeacherName();
                    JOptionPane.showMessageDialog(this, courseDetails, "Course Details", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Course not found.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error retrieving course: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid Course ID.", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewCourseButtonActionPerformedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseManagementGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButtonActionPerformed;
    private javax.swing.JButton backButtonActionPerformed;
    private javax.swing.JButton deleteCourseButtonActionPerformed;
    private javax.swing.JButton editCourseButtonActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewCourseButtonActionPerformed;
    // End of variables declaration//GEN-END:variables
}
