/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_information_management_system;

import javax.swing.JOptionPane;
import java.sql.SQLException;

public class StudentManagementGUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentManagementGUI
     */
    public StudentManagementGUI() {
        initComponents();
        setSize(790, 542);  
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addButtonActionPerformed = new javax.swing.JButton();
        editButtonActionPerformed = new javax.swing.JButton();
        viewStudentButtonActionPerformed = new javax.swing.JButton();
        deleteStudentButtonActionPerformed = new javax.swing.JButton();
        backButtonActionPerformed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Silom", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Management");

        addButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        addButtonActionPerformed.setText("Add Student Details");
        addButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformedActionPerformed(evt);
            }
        });

        editButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        editButtonActionPerformed.setText("Edit Student Details");
        editButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformedActionPerformed(evt);
            }
        });

        viewStudentButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        viewStudentButtonActionPerformed.setText("View Student Details");
        viewStudentButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentButtonActionPerformedActionPerformed(evt);
            }
        });

        deleteStudentButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        deleteStudentButtonActionPerformed.setText("Delete Student");
        deleteStudentButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButtonActionPerformedActionPerformed(evt);
            }
        });

        backButtonActionPerformed.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        backButtonActionPerformed.setText("Back");
        backButtonActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewStudentButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStudentButtonActionPerformed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewStudentButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteStudentButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButtonActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformedActionPerformed
        AddStudentGUI addStudentForm = new AddStudentGUI();
        addStudentForm.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_addButtonActionPerformedActionPerformed

    private void editButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformedActionPerformed
        EditStudentGUI editStudentForm = new EditStudentGUI();
        editStudentForm.setVisible(true);
        this.dispose(); // Close the StudentManagementGUI
    }//GEN-LAST:event_editButtonActionPerformedActionPerformed

    private void viewStudentButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentButtonActionPerformedActionPerformed
        String studentId = JOptionPane.showInputDialog(this, "Enter Student ID:", "View Student Details", JOptionPane.PLAIN_MESSAGE);

        if (studentId != null && !studentId.trim().isEmpty()) {
            try {
                // Use StudentDataManager to retrieve the student by ID
                StudentDataManager studentManager = new StudentDataManager();
                Student student = studentManager.getStudentById(studentId);

                if (student != null) {
                    // Display the student details in a message box or on the form
                    String studentDetails = "ID: " + student.getId() + "\n" +
                                            "Name: " + student.getName() + "\n" +
                                            "Age: " + student.getAge() + "\n" +
                                            "Address: " + student.getAddress();
                    JOptionPane.showMessageDialog(this, studentDetails, "Student Details", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Student not found.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error retrieving student: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid Student ID.", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_viewStudentButtonActionPerformedActionPerformed

    private void deleteStudentButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentButtonActionPerformedActionPerformed
        String studentId = JOptionPane.showInputDialog(this, "Enter Student ID to delete:", "Delete Student", JOptionPane.WARNING_MESSAGE);

        if (studentId != null && !studentId.trim().isEmpty()) {
            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the student with ID " + studentId + "?", "Confirm Deletion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    // Use StudentDataManager to delete the student by ID
                    StudentDataManager studentManager = new StudentDataManager();
                    studentManager.deleteStudent(studentId);

                    // Confirm that the student was deleted
                    JOptionPane.showMessageDialog(this, "Student with ID " + studentId + " deleted successfully.", "Delete Successful", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error deleting student: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Deletion cancelled.", "Cancelled", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter a valid Student ID.", "Input Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteStudentButtonActionPerformedActionPerformed

    private void backButtonActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformedActionPerformed
        PostLoginMenuGUI postLoginMenu = new PostLoginMenuGUI();
        postLoginMenu.setVisible(true);
        this.dispose(); // Close the StudentManagementGUI
    }//GEN-LAST:event_backButtonActionPerformedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagementGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButtonActionPerformed;
    private javax.swing.JButton backButtonActionPerformed;
    private javax.swing.JButton deleteStudentButtonActionPerformed;
    private javax.swing.JButton editButtonActionPerformed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewStudentButtonActionPerformed;
    // End of variables declaration//GEN-END:variables
}
